const BASE = {
  home: { fr:"Accueil", en:"Home", ar:"الرئيسية", es:"Inicio", pt:"Início", sw:"Nyumbani", ha:"Gida", wo:"Kër", am:"ቤት", ln:"Ndako", hi:"होम", bn:"হোম", ms:"Utama", tr:"Ana Sayfa", id:"Beranda", zh:"首页", ru:"Главная", de:"Startseite", it:"Home" },
  products: { fr:"Produits", en:"Products", ar:"المنتجات", es:"Productos", pt:"Produtos", sw:"Bidhaa", ha:"Kayayyaki", wo:"Jaamu", am:"ምርቶች", ln:"Biloko", hi:"उत्पाद", bn:"পণ্য", ms:"Produk", tr:"Ürünler", id:"Produk", zh:"产品", ru:"Товары", de:"Produkte", it:"Prodotti" },
  services: { fr:"Services", en:"Services", ar:"الخدمات", es:"Servicios", pt:"Serviços", sw:"Huduma", ha:"Aiyuka", wo:"Liggéey", am:"አገልግሎቶች", ln:"Mosala", hi:"सेवाएं", bn:"সেবা", ms:"Perkhidmatan", tr:"Hizmetler", id:"Layanan", zh:"服务", ru:"Услуги", de:"Dienste", it:"Servizi" },
  opportunities: { fr:"Opportunités", en:"Opportunities", ar:"الفرص", es:"Oportunidades", pt:"Oportunidades", sw:"Fursa", ha:"Damar", wo:"Yéégël", am:"እድሎች", ln:"Mikano", hi:"अवसर", bn:"সুযোগ", ms:"Peluang", tr:"Fırsatlar", id:"Peluang", zh:"机会", ru:"Возможности", de:"Möglichkeiten", it:"Opportunità" },
  flash_sales: { fr:"Ventes Flash", en:"Flash Sales", ar:"عروض فلاش", es:"Ventas Flash", pt:"Vendas Flash", sw:"Mauzo ya Haraka", ha:"Gwauron Siyarwa", wo:"Jaay bu gaaw", am:"ፍላሽ ሽያጮች", ln:"Bateka ya lomba", hi:"फ्लैश सेल", bn:"ফ্লাশ সেল", ms:"Jualan Kilat", tr:"Flaş Satışlar", id:"Flash Sale", zh:"闪购", ru:"Флеш-продажи", de:"Blitzverkäufe", it:"Vendite Flash" },
  alerts: { fr:"Alertes", en:"Alerts", ar:"التنبيهات", es:"Alertas", pt:"Alertas", sw:"Arifa", ha:"Gargaɗi", wo:"Xaamukaay", am:"ማስጠንቀቂያዎች", ln:"Bileli", hi:"अलर्ट", bn:"সতর্কতা", ms:"Amaran", tr:"Uyarılar", id:"Peringatan", zh:"提醒", ru:"Уведомления", de:"Benachrichtigungen", it:"Avvisi" },
  messages: { fr:"Messages", en:"Messages", ar:"الرسائل", es:"Mensajes", pt:"Mensagens", sw:"Ujumbe", ha:"Saƙo", wo:"Xbaar", am:"መልዕክቶች", ln:"Maloba", hi:"संदेश", bn:"বার্তা", ms:"Mesej", tr:"Mesajlar", id:"Pesan", zh:"消息", ru:"Сообщения", de:"Nachrichten", it:"Messaggi" },
  profile: { fr:"Profil", en:"Profile", ar:"الملف الشخصي", es:"Perfil", pt:"Perfil", sw:"Wasifu", ha:"Bayani", wo:"Profil", am:"መገለጫ", ln:"Profil", hi:"प्रोफ़ाइल", bn:"প্রোফাইল", ms:"Profil", tr:"Profil", id:"Profil", zh:"个人资料", ru:"Профиль", de:"Profil", it:"Profilo" },
  search: { fr:"Rechercher...", en:"Search...", ar:"بحث...", es:"Buscar...", pt:"Pesquisar...", sw:"Tafuta...", ha:"Nema...", wo:"Seet...", am:"ፈልግ...", ln:"Koluka...", hi:"खोजें...", bn:"খুঁজুন...", ms:"Cari...", tr:"Ara...", id:"Cari...", zh:"搜索...", ru:"Поиск...", de:"Suchen...", it:"Cerca..." },
  today_opportunities: { fr:"Opportunités du jour", en:"Today's Opportunities", ar:"فرص اليوم", es:"Oportunidades del día", pt:"Oportunidades de hoje", sw:"Fursa za leo", ha:"Damammaki na yau", wo:"Yéégël bii", am:"የዛሬ እድሎች", ln:"Mikano ya lelo", hi:"आज के अवसर", bn:"আজকের সুযোগ", ms:"Peluang Hari Ini", tr:"Bugünün Fırsatları", id:"Peluang Hari Ini", zh:"今日机会", ru:"Сегодняшние возможности", de:"Heutige Möglichkeiten", it:"Opportunità di oggi" },
  flash_deals: { fr:"Ventes Flash", en:"Flash Deals", ar:"عروض فلاش", es:"Ofertas Flash", pt:"Ofertas Flash", sw:"Ofa za Haraka", ha:"Kasuwar Lokaci", wo:"Njëlël yi", am:"ፍላሽ ቅናሾች", ln:"Esopo ya lomba", hi:"फ्लैश डील", bn:"ফ্লাশ ডিল", ms:"Tawaran Kilat", tr:"Flaş Fırsatlar", id:"Flash Deal", zh:"闪购优惠", ru:"Флеш-акции", de:"Blitzangebote", it:"Offerte Flash" },
  products_near: { fr:"Produits près de moi", en:"Products Near Me", ar:"منتجات بالقرب مني", es:"Productos cerca de mí", pt:"Produtos perto de mim", sw:"Bidhaa karibu nami", ha:"Kayayyaki kusa da ni", wo:"Jaamu yi ci kanam", am:"ለኔ ቅርብ ምርቶች", ln:"Biloko pene na ngai", hi:"मेरे पास उत्पाद", bn:"আমার কাছের পণ্য", ms:"Produk Berdekatan", tr:"Yakınımdaki Ürünler", id:"Produk Terdekat", zh:"附近产品", ru:"Товары рядом", de:"Produkte in der Nähe", it:"Prodotti vicino a me" },
  services_near: { fr:"Services près de moi", en:"Services Near Me", ar:"خدمات بالقرب مني", es:"Servicios cerca de mí", pt:"Serviços perto de mim", sw:"Huduma karibu nami", ha:"Aiyuka kusa da ni", wo:"Liggéey yi ci kanam", am:"ለኔ ቅርብ አገልግሎቶች", ln:"Mosala pene na ngai", hi:"मेरे पास सेवाएं", bn:"আমার কাছের সেবা", ms:"Perkhidmatan Berdekatan", tr:"Yakınımdaki Hizmetler", id:"Layanan Terdekat", zh:"附近服务", ru:"Услуги рядом", de:"Dienste in der Nähe", it:"Servizi vicino a me" },
  see_all: { fr:"Voir tout", en:"See All", ar:"عرض الكل", es:"Ver todo", pt:"Ver tudo", sw:"Ona yote", ha:"Duba duka", wo:"Xool yëp", am:"ሁሉን ይዩ", ln:"Tala nyonso", hi:"सब देखें", bn:"সব দেখুন", ms:"Lihat Semua", tr:"Tümünü Gör", id:"Lihat Semua", zh:"查看全部", ru:"Посмотреть все", de:"Alle sehen", it:"Vedi tutto" },
  publish: { fr:"Publier", en:"Publish", ar:"نشر", es:"Publicar", pt:"Publicar", sw:"Chapisha", ha:"Buga", wo:"Tekki", am:"አትም", ln:"Panza", hi:"प्रकाशित करें", bn:"প্রকাশ করুন", ms:"Terbitkan", tr:"Yayınla", id:"Terbitkan", zh:"发布", ru:"Опубликовать", de:"Veröffentlichen", it:"Pubblica" },
  buy: { fr:"Acheter", en:"Buy", ar:"شراء", es:"Comprar", pt:"Comprar", sw:"Nunua", ha:"Saya", wo:"Jënd", am:"ግዛ", ln:"Somb", hi:"खरीदें", bn:"কিনুন", ms:"Beli", tr:"Satın Al", id:"Beli", zh:"购买", ru:"Купить", de:"Kaufen", it:"Acquista" },
  contact: { fr:"Contacter", en:"Contact", ar:"اتصال", es:"Contactar", pt:"Contatar", sw:"Wasiliana", ha:"Tuntuɓi", wo:"Yëgël", am:"አግኙ", ln:"Bengana", hi:"संपर्क करें", bn:"যোগাযোগ", ms:"Hubungi", tr:"İletişim", id:"Hubungi", zh:"联系", ru:"Связаться", de:"Kontaktieren", it:"Contatta" },
  unlock: { fr:"Débloquer", en:"Unlock", ar:"فتح", es:"Desbloquear", pt:"Desbloquear", sw:"Fungua", ha:"Buɗe", wo:"Ubbi", am:"ክፈት", ln:"Fungola", hi:"अनलॉक करें", bn:"আনলক করুন", ms:"Buka Kunci", tr:"Kilidi Aç", id:"Buka Kunci", zh:"解锁", ru:"Разблокировать", de:"Entsperren", it:"Sblocca" },
  premium: { fr:"Premium", en:"Premium", ar:"مميز", es:"Premium", pt:"Premium", sw:"Premium", ha:"Madaukaki", wo:"Premium", am:"ፕሪሚየም", ln:"Premium", hi:"प्रीमियम", bn:"প্রিমিয়াম", ms:"Premium", tr:"Premium", id:"Premium", zh:"高级", ru:"Премиум", de:"Premium", it:"Premium" },
  free: { fr:"Gratuit", en:"Free", ar:"مجاني", es:"Gratis", pt:"Grátis", sw:"Bure", ha:"Kyauta", wo:"Dëkk", am:"ነፃ", ln:"Ofele", hi:"मुफ़्त", bn:"বিনামূল্যে", ms:"Percuma", tr:"Ücretsiz", id:"Gratis", zh:"免费", ru:"Бесплатно", de:"Kostenlos", it:"Gratis" },
  filters: { fr:"Filtres", en:"Filters", ar:"تصفية", es:"Filtros", pt:"Filtros", sw:"Vichujio", ha:"Tace", wo:"Yëbu", am:"ማጣሪያዎች", ln:"Bisaleli", hi:"फ़िल्टर", bn:"ফিল্টার", ms:"Penapis", tr:"Filtreler", id:"Filter", zh:"筛选", ru:"Фильтры", de:"Filter", it:"Filtri" },
  category: { fr:"Catégorie", en:"Category", ar:"الفئة", es:"Categoría", pt:"Categoria", sw:"Jamii", ha:"Rukunin", wo:"Wàll", am:"ምድብ", ln:"Etando", hi:"श्रेणी", bn:"বিভাগ", ms:"Kategori", tr:"Kategori", id:"Kategori", zh:"分类", ru:"Категория", de:"Kategorie", it:"Categoria" },
  price: { fr:"Prix", en:"Price", ar:"السعر", es:"Precio", pt:"Preço", sw:"Bei", ha:"Farashin", wo:"Njëg", am:"ዋጋ", ln:"Ntalo", hi:"कीमत", bn:"দাম", ms:"Harga", tr:"Fiyat", id:"Harga", zh:"价格", ru:"Цена", de:"Preis", it:"Prezzo" },
  location: { fr:"Localisation", en:"Location", ar:"الموقع", es:"Ubicación", pt:"Localização", sw:"Mahali", ha:"Wuri", wo:"Géej", am:"ቦታ", ln:"Esika", hi:"स्थान", bn:"অবস্থান", ms:"Lokasi", tr:"Konum", id:"Lokasi", zh:"位置", ru:"Местоположение", de:"Standort", it:"Posizione" },
  rating: { fr:"Note", en:"Rating", ar:"التقييم", es:"Calificación", pt:"Avaliação", sw:"Ukadiriaji", ha:"Daraja", wo:"Xam", am:"ደረጃ", ln:"Ntalo ya bolamu", hi:"रेटिंग", bn:"রেটিং", ms:"Penilaian", tr:"Derecelendirme", id:"Rating", zh:"评分", ru:"Рейтинг", de:"Bewertung", it:"Valutazione" },
  reviews: { fr:"Avis", en:"Reviews", ar:"المراجعات", es:"Reseñas", pt:"Avaliações", sw:"Maoni", ha:"Ra'ayoyi", wo:"Xalaatef", am:"ግምገማዎች", ln:"Makanisi", hi:"समीक्षाएं", bn:"পর্যালোচনা", ms:"Ulasan", tr:"Yorumlar", id:"Ulasan", zh:"评论", ru:"Отзывы", de:"Bewertungen", it:"Recensioni" },
  description: { fr:"Description", en:"Description", ar:"الوصف", es:"Descripción", pt:"Descrição", sw:"Maelezo", ha:"Bayani", wo:"Xamoone", am:"መግለጫ", ln:"Bolimboli", hi:"विवरण", bn:"বিবরণ", ms:"Penerangan", tr:"Açıklama", id:"Deskripsi", zh:"描述", ru:"Описание", de:"Beschreibung", it:"Descrizione" },
  seller: { fr:"Vendeur", en:"Seller", ar:"البائع", es:"Vendedor", pt:"Vendedor", sw:"Muuzaji", ha:"Mai siyarwa", wo:"Jaaykat", am:"ሻጭ", ln:"Moteki", hi:"विक्रेता", bn:"বিক্রেতা", ms:"Penjual", tr:"Satıcı", id:"Penjual", zh:"卖家", ru:"Продавец", de:"Verkäufer", it:"Venditore" },
  provider: { fr:"Prestataire", en:"Provider", ar:"مقدم الخدمة", es:"Proveedor", pt:"Fornecedor", sw:"Mtoa huduma", ha:"Mai ba da sabis", wo:"Jëfandikukat", am:"አቅራቢ", ln:"Mopesi", hi:"प्रदाता", bn:"সেবা প্রদানকারী", ms:"Pembekal", tr:"Sağlayıcı", id:"Penyedia", zh:"服务商", ru:"Поставщик", de:"Anbieter", it:"Fornitore" },
  status: { fr:"Statut", en:"Status", ar:"الحالة", es:"Estado", pt:"Estado", sw:"Hali", ha:"Matsayi", wo:"Yoon", am:"ሁኔታ", ln:"Bokeli", hi:"स्थिति", bn:"অবস্থা", ms:"Status", tr:"Durum", id:"Status", zh:"状态", ru:"Статус", de:"Status", it:"Stato" },
  active: { fr:"Actif", en:"Active", ar:"نشط", es:"Activo", pt:"Ativo", sw:"Amilifu", ha:"Mai aiki", wo:"Jëf", am:"ንቁ", ln:"Na mosala", hi:"सक्रिय", bn:"সক্রিয়", ms:"Aktif", tr:"Aktif", id:"Aktif", zh:"活跃", ru:"Активный", de:"Aktiv", it:"Attivo" },
  pending: { fr:"En attente", en:"Pending", ar:"قيد الانتظار", es:"Pendiente", pt:"Pendente", sw:"Inasubiri", ha:"Ana jira", wo:"Mujjee", am:"በመጠባበቅ ላይ", ln:"Ozali kosunga", hi:"लंबित", bn:"অপেক্ষারত", ms:"Tertangguh", tr:"Beklemede", id:"Menunggu", zh:"待处理", ru:"В ожидании", de:"Ausstehend", it:"In attesa" },
  sold: { fr:"Vendu", en:"Sold", ar:"مباع", es:"Vendido", pt:"Vendido", sw:"Umeuzwa", ha:"An sayar", wo:"Jaaye", am:"ተሸጠ", ln:"Batekaki", hi:"बेचा गया", bn:"বিক্রি হয়েছে", ms:"Terjual", tr:"Satıldı", id:"Terjual", zh:"已售", ru:"Продано", de:"Verkauft", it:"Venduto" },
  expired: { fr:"Expiré", en:"Expired", ar:"منتهي", es:"Expirado", pt:"Expirado", sw:"Imekwisha", ha:"Ya ƙare", wo:"Jeex na", am:"ጊዜው አለፈ", ln:"Esilaki", hi:"समाप्त", bn:"মেয়াদোত্তীর্ণ", ms:"Tamat Tempoh", tr:"Süresi Doldu", id:"Kadaluarsa", zh:"已过期", ru:"Истёк", de:"Abgelaufen", it:"Scaduto" },
  favorites: { fr:"Favoris", en:"Favorites", ar:"المفضلة", es:"Favoritos", pt:"Favoritos", sw:"Vipendwa", ha:"Abubuwa na son zuciya", wo:"Yéegël yi", am:"ተወዳጆች", ln:"Bilingami", hi:"पसंदीदा", bn:"প্রিয়", ms:"Kegemaran", tr:"Favoriler", id:"Favorit", zh:"收藏", ru:"Избранное", de:"Favoriten", it:"Preferiti" },
  subscription: { fr:"Abonnement", en:"Subscription", ar:"الاشتراك", es:"Suscripción", pt:"Assinatura", sw:"Usajili", ha:"Rajista", wo:"Abonnement", am:"የደንበኝነት ምዝገባ", ln:"Kofuta", hi:"सदस्यता", bn:"সদস্যতা", ms:"Langganan", tr:"Abonelik", id:"Langganan", zh:"订阅", ru:"Подписка", de:"Abonnement", it:"Abbonamento" },
  logout: { fr:"Déconnexion", en:"Logout", ar:"تسجيل الخروج", es:"Cerrar sesión", pt:"Sair", sw:"Toka", ha:"Fita", wo:"Dem", am:"ወጣ", ln:"Bima", hi:"लॉग आउट", bn:"লগ আউট", ms:"Log Keluar", tr:"Çıkış Yap", id:"Keluar", zh:"退出登录", ru:"Выйти", de:"Abmelden", it:"Esci" },
  login: { fr:"Connexion", en:"Login", ar:"تسجيل الدخول", es:"Iniciar sesión", pt:"Entrar", sw:"Ingia", ha:"Shiga", wo:"Dugg", am:"ግባ", ln:"Kota", hi:"लॉग इन", bn:"লগ ইন", ms:"Log Masuk", tr:"Giriş Yap", id:"Masuk", zh:"登录", ru:"Войти", de:"Anmelden", it:"Accedi" },
  dashboard: { fr:"Tableau de bord", en:"Dashboard", ar:"لوحة التحكم", es:"Panel", pt:"Painel", sw:"Dashibodi", ha:"Shafin Gudanarwa", wo:"Dashboard", am:"ዳሽቦርድ", ln:"Tableau de bord", hi:"डैशबोर्ड", bn:"ড্যাশবোর্ড", ms:"Papan Pemuka", tr:"Gösterge Paneli", id:"Dasbor", zh:"仪表板", ru:"Панель управления", de:"Dashboard", it:"Bacheca" },
  credits: { fr:"Crédits", en:"Credits", ar:"الاعتمادات", es:"Créditos", pt:"Créditos", sw:"Mikopo", ha:"Lamuni", wo:"Kredi", am:"ክሬዲቶች", ln:"Mikolo", hi:"क्रेडिट", bn:"ক্রেডিট", ms:"Kredit", tr:"Kredi", id:"Kredit", zh:"积分", ru:"Кредиты", de:"Guthaben", it:"Crediti" },
  subscribe: { fr:"S'abonner", en:"Subscribe", ar:"اشترك", es:"Suscribirse", pt:"Assinar", sw:"Jiandikisha", ha:"Yi rajista", wo:"Abonne", am:"ይመዝገቡ", ln:"Kokuta", hi:"सदस्यता लें", bn:"সাবস্ক্রাইব করুন", ms:"Langgan", tr:"Abone Ol", id:"Berlangganan", zh:"订阅", ru:"Подписаться", de:"Abonnieren", it:"Abbonati" },
  all: { fr:"Tout", en:"All", ar:"الكل", es:"Todo", pt:"Tudo", sw:"Yote", ha:"Duka", wo:"Yëp", am:"ሁሉ", ln:"Nyonso", hi:"सभी", bn:"সব", ms:"Semua", tr:"Tümü", id:"Semua", zh:"全部", ru:"Все", de:"Alle", it:"Tutto" },
  save: { fr:"Enregistrer", en:"Save", ar:"حفظ", es:"Guardar", pt:"Salvar", sw:"Hifadhi", ha:"Ajiye", wo:"Dëkk", am:"አስቀምጥ", ln:"Bika", hi:"सहेजें", bn:"সংরক্ষণ করুন", ms:"Simpan", tr:"Kaydet", id:"Simpan", zh:"保存", ru:"Сохранить", de:"Speichern", it:"Salva" },
  cancel: { fr:"Annuler", en:"Cancel", ar:"إلغاء", es:"Cancelar", pt:"Cancelar", sw:"Ghairi", ha:"Soke", wo:"Bàyyi", am:"ሰርዝ", ln:"Suka", hi:"रद्द करें", bn:"বাতিল করুন", ms:"Batal", tr:"İptal", id:"Batal", zh:"取消", ru:"Отмена", de:"Abbrechen", it:"Annulla" },
  delete: { fr:"Supprimer", en:"Delete", ar:"حذف", es:"Eliminar", pt:"Excluir", sw:"Futa", ha:"Goge", wo:"Taxawal", am:"ሰርዝ", ln:"Suka", hi:"हटाएं", bn:"মুছুন", ms:"Padam", tr:"Sil", id:"Hapus", zh:"删除", ru:"Удалить", de:"Löschen", it:"Elimina" },
  edit: { fr:"Modifier", en:"Edit", ar:"تعديل", es:"Editar", pt:"Editar", sw:"Hariri", ha:"Gyara", wo:"Soppi", am:"አስተካክል", ln:"Luka", hi:"संपादित करें", bn:"সম্পাদনা করুন", ms:"Edit", tr:"Düzenle", id:"Edit", zh:"编辑", ru:"Редактировать", de:"Bearbeiten", it:"Modifica" },
  close: { fr:"Fermer", en:"Close", ar:"إغلاق", es:"Cerrar", pt:"Fechar", sw:"Funga", ha:"Rufe", wo:"Taxawal", am:"ዝጋ", ln:"Zipa", hi:"बंद करें", bn:"বন্ধ করুন", ms:"Tutup", tr:"Kapat", id:"Tutup", zh:"关闭", ru:"Закрыть", de:"Schließen", it:"Chiudi" },
  no_results: { fr:"Aucun résultat", en:"No results", ar:"لا توجد نتائج", es:"Sin resultados", pt:"Sem resultados", sw:"Hakuna matokeo", ha:"Babu sakamako", wo:"Dara", am:"ምንም ውጤት የለም", ln:"Eloko te", hi:"कोई परिणाम नहीं", bn:"কোনো ফলাফল নেই", ms:"Tiada hasil", tr:"Sonuç yok", id:"Tidak ada hasil", zh:"无结果", ru:"Нет результатов", de:"Keine Ergebnisse", it:"Nessun risultato" },
  loading: { fr:"Chargement...", en:"Loading...", ar:"جار التحميل...", es:"Cargando...", pt:"Carregando...", sw:"Inapakia...", ha:"Ana lodawa...", wo:"Yëgëlaat...", am:"በመጫን ላይ...", ln:"Ekotomba...", hi:"लोड हो रहा है...", bn:"লোড হচ্ছে...", ms:"Memuatkan...", tr:"Yükleniyor...", id:"Memuat...", zh:"加载中...", ru:"Загрузка...", de:"Wird geladen...", it:"Caricamento..." },
  language: { fr:"Langue", en:"Language", ar:"اللغة", es:"Idioma", pt:"Idioma", sw:"Lugha", ha:"Harshe", wo:"Làmb", am:"ቋንቋ", ln:"Lokota", hi:"भाषा", bn:"ভাষা", ms:"Bahasa", tr:"Dil", id:"Bahasa", zh:"语言", ru:"Язык", de:"Sprache", it:"Lingua" },
  send: { fr:"Envoyer", en:"Send", ar:"إرسال", es:"Enviar", pt:"Enviar", sw:"Tuma", ha:"Aika", wo:"Yónnee", am:"ላክ", ln:"Tinda", hi:"भेजें", bn:"পাঠান", ms:"Hantar", tr:"Gönder", id:"Kirim", zh:"发送", ru:"Отправить", de:"Senden", it:"Invia" },
  type_message: { fr:"Tapez un message...", en:"Type a message...", ar:"اكتب رسالة...", es:"Escribe un mensaje...", pt:"Digite uma mensagem...", sw:"Andika ujumbe...", ha:"Rubuta saƙo...", wo:"Bind xbaar...", am:"መልዕክት ይጻፉ...", ln:"Koma liloba...", hi:"संदेश लिखें...", bn:"বার্তা লিখুন...", ms:"Taip mesej...", tr:"Mesaj yazın...", id:"Ketik pesan...", zh:"输入消息...", ru:"Введите сообщение...", de:"Nachricht eingeben...", it:"Scrivi un messaggio..." },
  welcome: { fr:"Bienvenue sur", en:"Welcome to", ar:"مرحبا بك في", es:"Bienvenido a", pt:"Bem-vindo ao", sw:"Karibu", ha:"Barka da zuwa", wo:"Dalal ak jàmm ci", am:"እንኳን ደህና መጡ", ln:"Boyei malamu na", hi:"स्वागत है", bn:"স্বাগতম", ms:"Selamat datang ke", tr:"Hoş geldiniz", id:"Selamat datang di", zh:"欢迎来到", ru:"Добро пожаловать в", de:"Willkommen bei", it:"Benvenuto su" },
  tagline: { fr:"Votre marketplace intelligente", en:"Your intelligent marketplace", ar:"سوقك الذكي", es:"Tu marketplace inteligente", pt:"Seu marketplace inteligente", sw:"Soko lako la akili", ha:"Kasuwarku ta hankali", wo:"Sa jëfandikukat bu xam-xam", am:"ብልህ ገበያዎ", ln:"Esika na yo ya bwanya", hi:"आपका स्मार्ट मार्केटप्लेस", bn:"আপনার স্মার্ট মার্কেটপ্লেস", ms:"Pasaran pintar anda", tr:"Akıllı pazaryeriniz", id:"Marketplace cerdas Anda", zh:"您的智能市场", ru:"Ваш умный маркетплейс", de:"Ihr intelligenter Marktplatz", it:"Il tuo marketplace intelligente" },
  budget: { fr:"Budget", en:"Budget", ar:"الميزانية", es:"Presupuesto", pt:"Orçamento", sw:"Bajeti", ha:"Kasafin kudi", wo:"Bujët", am:"በጀት", ln:"Budjet", hi:"बजट", bn:"বাজেট", ms:"Belanjawan", tr:"Bütçe", id:"Anggaran", zh:"预算", ru:"Бюджет", de:"Budget", it:"Budget" },
  urgency: { fr:"Urgence", en:"Urgency", ar:"الإلحاح", es:"Urgencia", pt:"Urgência", sw:"Haraka", ha:"Gaggawa", wo:"Xurma", am:"አስቸኳይ", ln:"Nalaka", hi:"तात्कालिकता", bn:"জরুরিতা", ms:"Kecemasan", tr:"Aciliyet", id:"Urgensi", zh:"紧急程度", ru:"Срочность", de:"Dringlichkeit", it:"Urgenza" },
  city: { fr:"Ville", en:"City", ar:"المدينة", es:"Ciudad", pt:"Cidade", sw:"Mji", ha:"Birni", wo:"Dëkk", am:"ከተማ", ln:"Engumba", hi:"शहर", bn:"শহর", ms:"Bandar", tr:"Şehir", id:"Kota", zh:"城市", ru:"Город", de:"Stadt", it:"Città" },
  country: { fr:"Pays", en:"Country", ar:"البلد", es:"País", pt:"País", sw:"Nchi", ha:"Ƙasa", wo:"Réew", am:"አገር", ln:"Mboka", hi:"देश", bn:"দেশ", ms:"Negara", tr:"Ülke", id:"Negara", zh:"国家", ru:"Страна", de:"Land", it:"Paese" },
  publish_product: { fr:"Publier un produit", en:"Publish Product", ar:"نشر منتج", es:"Publicar producto", pt:"Publicar produto", sw:"Chapisha bidhaa", ha:"Buga kaya", wo:"Tekki jaamu", am:"ምርት አትም", ln:"Panza eloko", hi:"उत्पाद प्रकाशित करें", bn:"পণ্য প্রকাশ করুন", ms:"Terbitkan Produk", tr:"Ürün Yayınla", id:"Terbitkan Produk", zh:"发布产品", ru:"Опубликовать товар", de:"Produkt veröffentlichen", it:"Pubblica prodotto" },
  publish_service: { fr:"Publier un service", en:"Publish Service", ar:"نشر خدمة", es:"Publicar servicio", pt:"Publicar serviço", sw:"Chapisha huduma", ha:"Buga aiyuka", wo:"Tekki liggéey", am:"አገልግሎት አትም", ln:"Panza mosala", hi:"सेवा प्रकाशित करें", bn:"সেবা প্রকাশ করুন", ms:"Terbitkan Perkhidmatan", tr:"Hizmet Yayınla", id:"Terbitkan Layanan", zh:"发布服务", ru:"Опубликовать услугу", de:"Dienst veröffentlichen", it:"Pubblica servizio" },
  available: { fr:"Disponible", en:"Available", ar:"متاح", es:"Disponible", pt:"Disponível", sw:"Inapatikana", ha:"Akwai", wo:"Ëmb", am:"ይገኛል", ln:"Ezo", hi:"उपलब्ध", bn:"উপলব্ধ", ms:"Tersedia", tr:"Müsait", id:"Tersedia", zh:"可用", ru:"Доступно", de:"Verfügbar", it:"Disponibile" },
  busy: { fr:"Occupé", en:"Busy", ar:"مشغول", es:"Ocupado", pt:"Ocupado", sw:"Amekuwa busy", ha:"Yana da aiki", wo:"Dëkk na", am:"ሥራ ላይ", ln:"Azali na mosala", hi:"व्यस्त", bn:"ব্যস্ত", ms:"Sibuk", tr:"Meşgul", id:"Sibuk", zh:"忙碌", ru:"Занят", de:"Beschäftigt", it:"Occupato" },
  offline: { fr:"Hors ligne", en:"Offline", ar:"غير متصل", es:"Sin conexión", pt:"Offline", sw:"Nje ya mtandao", ha:"Ba kan layi ba", wo:"Wañ", am:"ከኔት ዎርክ ውጭ", ln:"Longwa na réseau", hi:"ऑफ़लाइन", bn:"অফলাইন", ms:"Luar Talian", tr:"Çevrimdışı", id:"Offline", zh:"离线", ru:"Не в сети", de:"Offline", it:"Offline" },
  title: { fr:"Titre", en:"Title", ar:"العنوان", es:"Título", pt:"Título", sw:"Kichwa", ha:"Taken", wo:"Tuur末", am:"ርዕስ", ln:"Motindo", hi:"शीर्षक", bn:"শিরোনাম", ms:"Tajuk", tr:"Başlık", id:"Judul", zh:"标题", ru:"Заголовок", de:"Titel", it:"Titolo" },
  views: { fr:"Vues", en:"Views", ar:"المشاهدات", es:"Vistas", pt:"Visualizações", sw:"Maoni", ha:"Kallon", wo:"Xool", am:"እይታዎች", ln:"Botaleli", hi:"व्यूज़", bn:"ভিউ", ms:"Paparan", tr:"Görüntülemeler", id:"Tampilan", zh:"浏览量", ru:"Просмотры", de:"Aufrufe", it:"Visualizzazioni" },
  admin: { fr:"Admin", en:"Admin", ar:"الإدارة", es:"Admin", pt:"Admin", sw:"Msimamizi", ha:"Mai gudanarwa", wo:"Boroom", am:"አስተዳዳሪ", ln:"Motamboli", hi:"एडमिन", bn:"অ্যাডমিন", ms:"Admin", tr:"Yönetici", id:"Admin", zh:"管理员", ru:"Администратор", de:"Admin", it:"Admin" },
  my_listings: { fr:"Mes annonces", en:"My Listings", ar:"قوائمي", es:"Mis anuncios", pt:"Meus anúncios", sw:"Matangazo yangu", ha:"Iyadana", wo:"Xéet yi", am:"የኔ ማስታወቂያዎች", ln:"Bilɔbi na ngai", hi:"मेरे विज्ञापन", bn:"আমার তালিকা", ms:"Senarai Saya", tr:"Listelerim", id:"Daftar Saya", zh:"我的列表", ru:"Мои объявления", de:"Meine Anzeigen", it:"I miei annunci" },
  score: { fr:"Score", en:"Score", ar:"النتيجة", es:"Puntuación", pt:"Pontuação", sw:"Alama", ha:"Maki", wo:"Njëg", am:"ነጥብ", ln:"Puan", hi:"स्कोर", bn:"স্কোর", ms:"Skor", tr:"Puan", id:"Skor", zh:"分数", ru:"Счёт", de:"Punkte", it:"Punteggio" },
  margin: { fr:"Marge", en:"Margin", ar:"الهامش", es:"Margen", pt:"Margem", sw:"Faida", ha:"Riba", wo:"Bànneex", am:"ትርፍ", ln:"Benefis", hi:"मार्जिन", bn:"মার্জিন", ms:"Margin", tr:"Marj", id:"Margin", zh:"利润", ru:"Маржа", de:"Marge", it:"Margine" },
  select_plan: { fr:"Choisir un plan", en:"Select a Plan", ar:"اختر خطة", es:"Seleccionar plan", pt:"Selecionar plano", sw:"Chagua mpango", ha:"Zaɓi shiri", wo:"Tann plan", am:"እቅድ ምረጥ", ln:"Pona plan", hi:"प्लान चुनें", bn:"পরিকল্পনা বেছে নিন", ms:"Pilih Pelan", tr:"Plan Seç", id:"Pilih Paket", zh:"选择套餐", ru:"Выбрать план", de:"Plan wählen", it:"Seleziona piano" },
  discount: { fr:"Remise", en:"Discount", ar:"خصم", es:"Descuento", pt:"Desconto", sw:"Punguzo", ha:"Ragi", wo:"Dëgër", am:"ቅናሽ", ln:"Ndimbola", hi:"छूट", bn:"ছাড়", ms:"Diskaun", tr:"İndirim", id:"Diskon", zh:"折扣", ru:"Скидка", de:"Rabatt", it:"Sconto" },
  service_requests: { fr:"Demandes de service", en:"Service Requests", ar:"طلبات الخدمة", es:"Solicitudes de servicio", pt:"Pedidos de serviço", sw:"Maombi ya huduma", ha:"Bukatun aiyuka", wo:"Xam-xam liggéey", am:"የአገልግሎት ጥያቄዎች", ln:"Zopesami ya mosala", hi:"सेवा अनुरोध", bn:"সেবা অনুরোধ", ms:"Permintaan Perkhidmatan", tr:"Hizmet Talepleri", id:"Permintaan Layanan", zh:"服务请求", ru:"Запросы на услуги", de:"Serviceanfragen", it:"Richieste di servizio" },
  conversations: { fr:"Conversations", en:"Conversations", ar:"المحادثات", es:"Conversaciones", pt:"Conversas", sw:"Mazungumzo", ha:"Tattaunawa", wo:"Xanaamiyu", am:"ውይይቶች", ln:"Biteyano", hi:"बातचीत", bn:"কথোপকথন", ms:"Perbualan", tr:"Konuşmalar", id:"Percakapan", zh:"对话", ru:"Разговоры", de:"Gespräche", it:"Conversazioni" },
  my_alerts: { fr:"Mes alertes", en:"My Alerts", ar:"تنبيهاتي", es:"Mis alertas", pt:"Meus alertas", sw:"Arifa zangu", ha:"Gargaɗin na", wo:"Xaamukaay yii", am:"የኔ ማስጠንቀቂያዎች", ln:"Bileli na ngai", hi:"मेरे अलर्ट", bn:"আমার সতর্কতা", ms:"Amaran Saya", tr:"Uyarılarım", id:"Peringatan Saya", zh:"我的提醒", ru:"Мои уведомления", de:"Meine Benachrichtigungen", it:"I miei avvisi" },
  mark_read: { fr:"Marquer comme lu", en:"Mark as Read", ar:"تعيين كمقروء", es:"Marcar como leído", pt:"Marcar como lido", sw:"Weka kama umesomwa", ha:"Nuna an karanta", wo:"Tekki ko xamaloo", am:"እንደ ተነበበ ምልክት አድርግ", ln:"Yeba kokomami", hi:"पढ़ा हुआ चिह्नित करें", bn:"পঠিত হিসেবে চিহ্নিত করুন", ms:"Tandai sebagai Dibaca", tr:"Okundu Olarak İşaretle", id:"Tandai Dibaca", zh:"标为已读", ru:"Отметить как прочитанное", de:"Als gelesen markieren", it:"Segna come letto" },
  choose_language: { fr:"Choisir la langue", en:"Choose Language", ar:"اختر اللغة", es:"Elegir idioma", pt:"Escolher idioma", sw:"Chagua lugha", ha:"Zaɓi harshe", wo:"Tann làmb", am:"ቋንቋ ምረጥ", ln:"Pona lokota", hi:"भाषा चुनें", bn:"ভাষা বেছে নিন", ms:"Pilih Bahasa", tr:"Dil Seçin", id:"Pilih Bahasa", zh:"选择语言", ru:"Выбрать язык", de:"Sprache wählen", it:"Scegli lingua" },
};

export function getStoredLang() {
  return localStorage.getItem('app_lang') || 'fr';
}

export function setStoredLang(lang) {
  localStorage.setItem('app_lang', lang);
}

export function t(key) {
  const lang = getStoredLang();
  const row = BASE[key];
  if (!row) return key;
  return row[lang] || row['fr'] || row['en'] || key;
}

export function isRTL() {
  return ['ar', 'he', 'fa', 'ur'].includes(getStoredLang());
}

export const LANGUAGES = [
  // Afrique de l'Ouest & Centrale
  { code: 'fr',  label: 'Français',    flag: '🇫🇷',  region: 'Afrique / Europe' },
  { code: 'wo',  label: 'Wolof',       flag: '🇸🇳',  region: 'Afrique de l\'Ouest' },
  { code: 'ha',  label: 'Hausa',       flag: '🇳🇬',  region: 'Afrique de l\'Ouest' },
  { code: 'ln',  label: 'Lingala',     flag: '🇨🇩',  region: 'Afrique Centrale' },
  // Afrique de l'Est
  { code: 'sw',  label: 'Kiswahili',   flag: '🇰🇪',  region: 'Afrique de l\'Est' },
  { code: 'am',  label: 'አማርኛ',       flag: '🇪🇹',  region: 'Afrique de l\'Est' },
  // Monde
  { code: 'en',  label: 'English',     flag: '🇬🇧',  region: 'Monde' },
  { code: 'ar',  label: 'العربية',     flag: '🇸🇦',  region: 'Moyen-Orient' },
  { code: 'es',  label: 'Español',     flag: '🇪🇸',  region: 'Amérique Latine' },
  { code: 'pt',  label: 'Português',   flag: '🇧🇷',  region: 'Amérique Latine' },
  { code: 'hi',  label: 'हिन्दी',      flag: '🇮🇳',  region: 'Asie du Sud' },
  { code: 'bn',  label: 'বাংলা',       flag: '🇧🇩',  region: 'Asie du Sud' },
  { code: 'ms',  label: 'Bahasa Melayu', flag: '🇲🇾', region: 'Asie du Sud-Est' },
  { code: 'id',  label: 'Bahasa Indonesia', flag: '🇮🇩', region: 'Asie du Sud-Est' },
  { code: 'tr',  label: 'Türkçe',      flag: '🇹🇷',  region: 'Europe / Asie' },
  { code: 'ru',  label: 'Русский',     flag: '🇷🇺',  region: 'Europe de l\'Est' },
  { code: 'de',  label: 'Deutsch',     flag: '🇩🇪',  region: 'Europe' },
  { code: 'it',  label: 'Italiano',    flag: '🇮🇹',  region: 'Europe' },
  { code: 'zh',  label: '中文',         flag: '🇨🇳',  region: 'Asie de l\'Est' },
];